version: "3"

include:
  - microservices/docker-compose.yml

services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_USER_SERVICE_ENDPOINT: http://localhost:3001
        VITE_QUESTION_SERVICE_ENDPOINT: http://localhost:3002
        VITE_MATCHING_SERVICE_ENDPOINT: http://localhost:3003
        VITE_COLLABORATION_SERVICE_ENDPOINT: http://localhost:3004
    depends_on:
      - user_service_app
      - question_service_app
    restart: always
    networks:
      - user_service_public
      - question_service_public
    ports:
      - "0.0.0.0:80:80"


