name: Lint

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

permissions: read-all

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write # To report GitHub Actions status checks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
      - name: Super-linter
        uses: super-linter/super-linter@v6.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # To report GitHub Actions status checks
          FILTER_REGEX_EXCLUDE: (user-service/README\.md|user-service/\.env\.sample)
          VALIDATE_JAVASCRIPT_STANDARD: false
      - name: Linters not handled by Super-linter
        run: |
          # frontend
          cd frontend
          npm i
          npm run lint
          cd -
