name: Manual Super-Linter on Matching Service Branch

on:
  workflow_dispatch: # This enables manual triggering of the workflow
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

permissions: read-all

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write # To report GitHub Actions status checks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Super-linter needs the full git history

      - name: Super-linter
        uses: super-linter/super-linter@v6.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For GitHub Actions status checks
          FILTER_REGEX_EXCLUDE: (user-service/README\.md|user-service/\.env\.sample)
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_TSX: false
          VALIDATE_TYPESCRIPT_ES: false
          DEFAULT_BRANCH: matching-services

      - name: Linters not handled by Super-linter
        run: |
          # frontend
          cd frontend && npm i && npm run lint && cd -

          # matching-service
          cd microservices/matching-service && npm i && npm run lint && cd -

          # collaboration-service
          cd microservices/collaboration-service && npm i && npm run lint && cd -
